// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteEvent is an autogenerated mock type for the DeleteEvent type
type DeleteEvent struct {
	mock.Mock
}

// DeleteEvent provides a mock function with given fields: userID, eventID
func (_m *DeleteEvent) DeleteEvent(userID int64, eventID int64) error {
	ret := _m.Called(userID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(userID, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeleteEvent creates a new instance of DeleteEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteEvent {
	mock := &DeleteEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
