// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpdateEvent is an autogenerated mock type for the UpdateEvent type
type UpdateEvent struct {
	mock.Mock
}

// UpdateEvent provides a mock function with given fields: userID, eventID, dateStr, text
func (_m *UpdateEvent) UpdateEvent(userID int64, eventID int64, dateStr string, text string) error {
	ret := _m.Called(userID, eventID, dateStr, text)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, string, string) error); ok {
		r0 = rf(userID, eventID, dateStr, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUpdateEvent creates a new instance of UpdateEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateEvent {
	mock := &UpdateEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
